### ISSUE TITLE
Github page image

### ISSUE THREAD

**Issue by rishi420** [rishi420/Bonsai#1]
![github](https://user-images.githubusercontent.com/2233857/46226655-cbf61d80-c37e-11e8-9d2b-3d69177988a1.png)

**Comment by rishi420** [comment]
<img width="480" alt="screenshot 2018-10-23 at 12 06 41 pm" src="https://user-images.githubusercontent.com/2233857/47339168-3703ed00-d6bc-11e8-8220-4706e716d103.png">

**Comment by xRuby** [comment]
@rishi420   there is an error, i use object-c turn it, help 
<img width="930" alt="2018-11-19 7 39 52" src="https://user-images.githubusercontent.com/11939075/48705182-71b56280-ec33-11e8-8e40-bda8d66e19a0.png">


-

**Comment by xRuby** [comment]
not call    " func animateTransition(using transitionContext: UIViewControllerContextTransitioning) "

**Comment by rishi420** [comment]
@xRuby please show me how to create this crash. I have an Objective-C example `ObjectiveCViewController.m`. Can I change something to make the crash in the example project?

**Comment by xRuby** [comment]
thank you so much, i have resolve it, it's an error of mine.  ^_^
